repos:

  # precommit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  # black, isort
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort . --profile black
        language: system
        types: [python]
        pass_filenames: false
      - id: black
        name: black
        entry: black .
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [python]
        pass_filenames: false
#      - id: pytest
#        name: pytest
#        entry: pytest .
#        language: system
#        types: [python]
#        pass_filenames: false
