kernel_sax:
    kernel: 'epanechnikov'
    bandwidth: 0.5
    alphabet_size: 7
    epochs: 100
    boundary_estimation: 'lloyd_max'
    verbose: True
    random_state: 42


training:
    epochs: 100
    batch_size: 32
