name: Tests

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    #--------------------------
    # Check out repo and python
    #--------------------------
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        sparse_checkout: |
            /src/*
            /experiments/*
            /Pyraformer/*
            /tests/*
            /requirements.txt
            /.flake8
        sparse-checkout-cone-mode: false


    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    #--------------------------
    # Install dependencies
    #--------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip --user --verbose
        python -m pip install -r requirements.txt --user --verbose
        python -m pip install -e . --user --verbose

    #--------------------------
    # Code compliance
    #--------------------------
    - name: Code style compliance with black
      run: |
          python -m black --check .

    - name: Code style compliance with isort
      run: |
          python -m isort --check . --profile black

    - name: Linting with flake8
      run: |
          python -m flake8 .

    #--------------------------
    # Run tests
    #--------------------------
    - name: Run pytest with coverage
      run: |
          pytest --cov=src/ --cov-report=html tests/
      env:
          CI: true
